/**
 * Shared schema primitives.
 */

import { z } from "zod";

/**
 * A UUID-format string (8-4-4-4-12 hex), matching what Postgres's `uuid` type
 * accepts. We deliberately do NOT use Zod's `.uuid()`, which additionally
 * enforces RFC-4122 version/variant bits — Postgres does not, so a perfectly
 * valid DB id (e.g. one not generated by gen_random_uuid) would otherwise throw
 * on parse and 500 the page. These ids come from trusted DB columns, so a
 * format check is the correct level of validation.
 */
export const uuidString = z
  .string()
  .regex(
    /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
    "Invalid UUID",
  );
